sudo: false
dist: trusty
language: g++
compiler:
- g++
addons:
  apt:
    packages:
    - gcc-mingw-w64-x86-64
    - binutils-mingw-w64-x86-64
    - zip
script:
- '[ -z "$TRAVIS_TAG" ] || SW_VER=-DSW_VER=L\"$TRAVIS_TAG\"'
- mkdir out zip
- x86_64-w64-mingw32-gcc -std=c99 --pedantic -Wall -Wno-implicit-function-declaration
  --static main.c -lshlwapi -o out/Launcher.exe $SW_VER
- find  ./res/* -maxdepth 1 -type d -printf '%f\n' > resl.txt
- xargs -a resl.txt -I{} x86_64-w64-mingw32-windres res/{}/res.rc -o res/{}.o
- xargs -a resl.txt -I{} x86_64-w64-mingw32-gcc -std=c99 --pedantic -Wall -Wno-implicit-function-declaration
  --static main.c -lshlwapi res/{}.o -o zip/{}.exe $SW_VER
- cd zip
- zip ../out/icons.zip *
- cd ..
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: E/dyPQx9MfWtzgenKyrBoGS+p1xveRlGCnEID9+9dTxGEVJCSh9UL5jb8xFvAPIPtCU0LVcSOhkCt6FSydQxFmu0CyqJcdbfnKoDaUj7c8TLtisx/mk+gxdt1sSn1aJYyzBQCXLNOPkiONezCBA5lR58PNPXH47n2/ugkgm3Sg63WWqIuZWgefMTkrScK9c13TV9kpnZ/ODzJRY6EKzZ12eCwwsRdAAb/Yc7F020JdughiLBkDqLyZ7glZ2gnoi61lPPgqEXh8oWfjTo6ke6ClzDOKGyMukJ2JwIz9jXSsfNqUfOq8kEIvLnPeamKwU7Np1DAt3oFaNRI8407WBW/6eiC1ysuEA4m9c42WWQ9I7bLNmH6mog6IVPsOE1MERuPDCIAKgm3SeFD+JHZvRW2u+wbQBJOmmsYAcpQjjDjhtRjtdgHDC+V9AgcUM/PmnuuPtABn13bEepp+nZYg2gfmVD7Z9sTS520PLY/vuxx774YwbGF4W41OxlXAa4jPoC4sJ3fpHimdgxJqZTbupW9M9vygl6fw+KHkXjubxQndpw+BHVlmLkPVXdGf8z8ThXlRYHTkz9nrSbqguLhpeuH1vKfEaeEyISz8e7sH22TgcVpo7ubhpvFUPFtResgbnzgLOfaEuPPThLrW2MAPFie4OG7jLjAn5zEEITgXKFN2c=
  file_glob: true
  file: 'out/*.{exe,zip}'
  on:
    repo: kokkiemouse/wsldl
    tags: true
    all_branches: true
  skip_cleanup: 'true'
